### ISSUE TITLE
Review Utils functions for refactor or whether they're still needed

### ISSUE THREAD

**Issue by kingo55** [mint-metrics/mojito-js-delivery#64]
Some of the utils functions may be replaceable (arrayIndexOf, extend, keys):

https://github.com/kingo55/mojito-js-delivery/blob/9f313bd1ba59f1f8dcb80cc4df41b6b02b08f28c/lib/mojito.js#L515-L571

Older browsers are a dying breed and we probably don't need to offer shims for such old browsers that probably don't work on our clients' sites anyway.

**Comment by kingo55** [comment]
@allmywant do you think we need these three functions in the Utils lib? Or are there better ways of getting what we need here?

**Comment by allmywant** [comment]
@kingo55 
- arrayIndexOf: native Array.indexOf is widely supported: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf#Browser_compatibility
- keys: Object.keys is widely supported too: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys#Browser_compatibility
- extend: we can replace it with Object.assign, but IE doesn't support this (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility). Since we just call ```extend``` once, we can remove it and do it in place where we call ```extend```

Anyway I think all three functions can be removed.

**Comment by kingo55** [comment]
In the case of "extend", should we just leave that then? 

It's probably easier to keep the utility function code separate from the constructor code.

I think the other two can probably be safely removed / replaced though.

**Comment by allmywant** [comment]
You're right @kingo55 , let's keep "extend" and remove arrayIndexOf, keys.

**Comment by kingo55** [comment]
Addressed by #80
